name: Test Run

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix up git URLs for submodules
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run script
        run: |
          ls -la Dest_repo
