name: Test Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api octocat

      - name: Check Last Workflow Run
        if: github.event_name == 'push'
        env:
          REPOSITORY_DISPATCH_TOKEN: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          curl -s \
          -H 'Accept: application/vnd.github.v3+json' \
          -H "Authorization: token ${REPOSITORY_DISPATCH_TOKEN}" \
          "https://api.github.com/repos/SaswatiAssessio/testng-gradle-example?branch=main&per_page=1"

      - name: Trigger
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -X POST \
          -H 'Accept: application/vnd.github.v3+json' \
          -H "Authorization: token ${{ secrets.APP_PRIVATE_KEY }}" \
          --data '{"event_type": "printpr"}' \
          https://api.github.com/repos/assessio/Dest_repo/dispatches

  
