name: Test Run

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPENDABOT_POC }}
          submodules: true

      - name: Run script
        run: |
          ls -la Dest_repo
